load("@bazel_tools//tools/cpp:cc_configure.bzl", "cc_configure")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
cc_configure()

http_archive(
    name = "parlaylib",
    sha256 = "68c062ad116fd49d77651d7a24fb985aa66e8ec9ad05176b6af3ab5d29a16b1f",
    strip_prefix = "parlaylib-bazel/include/",
    urls = ["https://github.com/ParAlg/parlaylib/archive/refs/tags/bazel.tar.gz"],
)
