load("@bazel_tools//tools/cpp:cc_configure.bzl", "cc_configure")
cc_configure()

local_repository(
    name = "parlaylib",
    #path = "/usr0/home/ldhulipa/current/gbbs_feature/external/parlaylib/include",
    path = "../../parlaylib/include",
)
